.catalog:
  name: “F5 LB”
  version: "v0.1.0-rancher1"
  description: "Rancher External LB service powered by F5 BigIP."
  questions:
    - variable: "F5_BIGIP_HOST"
      label: "F5 BIGIP HOST"
      description: “Address of the F5 Host”
      type: "string"
      required: true
    - variable: "F5_BIGIP_USER"
      label: "F5 BIGIP USER"
      description: “Username of the F5 admin”
      type: "string"
      required: true
    - variable: "F5_BIGIP_PWD"
      label: "F5 BIGIP PWD"
      description: “Password of the F5 admin“
      type: "string"
      required: true
external-lb:
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
